import events as e
# Hyper parameters -- DO modify
TRANSITION_HISTORY_SIZE = 7  # keep only ... last transitions
RECORD_ENEMY_TRANSITIONS = 1.0  # record enemy transitions with probability ...

LEARNING_RATE = 0.4
DISCOUNT = 0.95
SAVE_EVERY = 1000
'''
game_rewards = {
    e.COIN_COLLECTED: 100,
    e.KILLED_OPPONENT: 5,
    e.INVALID_ACTION: -50,
    e.MOVED_LEFT: -1,
    e.MOVED_DOWN: -1,
    e.MOVED_UP: -1,
    e.MOVED_RIGHT: -1,
    e.WAITED: -30,
    "COIN_LESSDISTANCE": 20,
    "COIN_SAMEDISTANCE": -2,
    "COIN_MOREDISTANCE": -20,
    "CRATE_LESSDISTANCE": 2,
    "CRATE_SAMEDISTANCE": 0,
    "CRATE_MOREDISTANCE": -2,
    "BOMB_LESSDISTANCE": -10,
    "BOMB_SAMEDISTANCE": -2,
    "BOMB_MOREDISTANCE": 10,
    "DEADEND_LESSDISTANCE": 2,
    "DEADEND_SAMEDISTANCE": 0,
    "DEADEND_MOREDISTANCE": -2,
    "BOMB_RISK_EVENT": -100,
    "BOMB_SAVING_EVENT": 100,
    "DEADEND_BOMB": 100,
    "FREESPACE_BOMB": -100,
    "WRONG_WAIT": -50,
    "BOMB_DROPPED_WRONGTIME": -100,
    e.BOMB_DROPPED: -5,
    e.BOMB_EXPLODED: 10,
    e.CRATE_DESTROYED: 150,
    e.KILLED_SELF: -200,
    e.GOT_KILLED: -200,
    e.SURVIVED_ROUND: 400
}'''


game_rewards = {
    e.COIN_COLLECTED: 100,
    e.KILLED_OPPONENT: 5,
    e.INVALID_ACTION: -50,
    e.MOVED_LEFT: -1,
    e.MOVED_DOWN: -1,
    e.MOVED_UP: -1,
    e.MOVED_RIGHT: -1,
    e.WAITED: -5,
    "COIN_LESSDISTANCE": 20,
    "COIN_SAMEDISTANCE": -2,
    "COIN_MOREDISTANCE": -20,
    "CRATE_LESSDISTANCE": 2,
    "CRATE_SAMEDISTANCE": 0,
    "CRATE_MOREDISTANCE": -2,
    "BOMB_LESSDISTANCE": -50,
    "BOMB_SAMEDISTANCE": -2,
    "BOMB_MOREDISTANCE": 50,
    "BOMB_RISK_EVENT": -150,
    "BOMB_SAVING_EVENT": 150,
    "DEADEND_BOMB": 150,
    "FREESPACE_BOMB": -50,
    "WRONG_WAIT": -50,
    "BOMB_DROPPED_WRONGTIME": -100,
    e.BOMB_DROPPED: -50,
    e.BOMB_EXPLODED: 50,
    e.CRATE_DESTROYED: 50,
    e.KILLED_SELF: -600,
    e.GOT_KILLED: -200,
    e.SURVIVED_ROUND: 200
}
